const { contextBridge, ipcRenderer } = require('electron')
contextBridge.exposeInMainWorld('sw', {
  close:            ()             => ipcRenderer.send('close'),
  toggleSidebar:    ()             => ipcRenderer.send('toggle-sidebar'),
  contextMenu:      ()             => ipcRenderer.send('context-menu'),
  charMove:         (x, y)         => ipcRenderer.send('char-move', { x, y }),
  moveSidebar:      (x, y)         => ipcRenderer.send('move-sidebar', { x, y }),
  getSidebarPos:    ()             => ipcRenderer.invoke('get-sidebar-pos'),
  getScreen:        ()             => ipcRenderer.invoke('get-screen'),
  getCursor:        ()             => ipcRenderer.invoke('get-cursor'),
  getWindows:       ()             => ipcRenderer.invoke('get-windows'),
  screenshot:       ()             => ipcRenderer.invoke('screenshot'),
  winFocus:         (title)        => ipcRenderer.invoke('win-focus', title),
  sendKeys:         (text)         => ipcRenderer.invoke('send-keys', text),
  mouseClick:       (x, y)         => ipcRenderer.invoke('mouse-click', x, y),
  doubleClick:      (x, y)         => ipcRenderer.invoke('double-click', { x, y }),
  smartDoubleClick: (x, y)         => ipcRenderer.invoke('smart-double-click', { x, y }),
  revealTaskbar:    ()             => ipcRenderer.invoke('reveal-taskbar'),
  openFolder:       (path)         => ipcRenderer.send('open-folder', path),
  launchByName:     (name)         => ipcRenderer.invoke('launch-by-name', name),
  openViaSearch:    (name)         => ipcRenderer.invoke('open-via-search', name),
  requestFlyClick:  (sx,sy,lbl)    => ipcRenderer.send('request-fly-click', { screenX:sx, screenY:sy, label:lbl }),
  onFlyToClick:     (cb)           => ipcRenderer.on('fly-to-click', (e, d) => cb(d)),
  openApp:          (id)           => ipcRenderer.send('open-app', id),
  openUrl:          (url)          => ipcRenderer.send('open-url', url),
  launcherMove:     (x, y)         => ipcRenderer.send('launcher-move', { x, y }),
  launcherPos:      ()             => ipcRenderer.invoke('launcher-pos'),
  launcherContext:  ()             => ipcRenderer.send('launcher-context'),
  sidebarVisible:   ()             => ipcRenderer.invoke('sidebar-visible'),
  onSidebarState:   (cb)           => ipcRenderer.on('sidebar-state', (e, v) => cb(v)),
  onOpenSettings:   (cb)           => ipcRenderer.on('open-settings', cb),
  setQuip:          (text, duration, mood, source) => ipcRenderer.send('set-quip', { text, duration, mood, source }),
  onShowQuip:       (cb)           => ipcRenderer.on('show-quip', (e, d) => cb(d)),
  getState:             ()        => ipcRenderer.invoke('state-get'),
  patchState:           (partial) => ipcRenderer.send('state-patch', partial),
  clearConversation:    ()        => ipcRenderer.send('state-clear-conversation'),
  onHelperInit:         (cb)      => ipcRenderer.on('helper-init', (e, d) => cb(d)),
  helperPick:           (payload) => ipcRenderer.send('helper-pick', payload),
  helperCancel:         ()        => ipcRenderer.send('helper-cancel'),
  onQuickInsight:       (cb)      => ipcRenderer.on('quick-insight', (e, d) => cb(d)),
  startPomodoro:        (opts)    => ipcRenderer.invoke('pomodoro-start', opts),
  pomodoroStatus:       ()        => ipcRenderer.invoke('pomodoro-status'),
  cancelPomodoro:       ()        => ipcRenderer.invoke('pomodoro-cancel'),
  onPomodoroTick:       (cb)      => ipcRenderer.on('pomodoro-tick', (e, d) => cb(d)),
  cancelPomodoroFromPanel: ()     => ipcRenderer.send('pomodoro-panel-cancel'),
  openManual:           ()        => ipcRenderer.send('open-manual'),
  convertFile:          (srcPath, target) => ipcRenderer.invoke('convert-file', { srcPath, target }),
  convertTargets:       (srcPath)         => ipcRenderer.invoke('convert-targets', srcPath),
  shortcutStatus:       ()        => ipcRenderer.invoke('shortcut-status'),
  shortcutCreate:       ()        => ipcRenderer.invoke('shortcut-create'),
  shortcutRemove:       ()        => ipcRenderer.invoke('shortcut-remove'),
  setUiScale:           (scale)   => ipcRenderer.invoke('set-ui-scale', scale),
})
